# SPDX-License-Identifier: GPL-2.0-or-later

load("@rules_devicetree//devicetree:dtb.bzl", "dtb")
load("@rules_devicetree//devicetree:devicetree_library.bzl", "devicetree_library")

package(default_visibility = ["//vendor/nvidia:__subpackages__"])

devicetree_library(
    name = "all_t21x_dtsi",
    hdrs = glob([
        "*.dtsi",
        "*.dts",
    ]),
    includes = ["."],
)

dtb(
    name = "tegra210-baracus.dtb",
    srcs = ["tegra210-baracus.dts"],
    generate_symbols = True,
    deps = [
        ":all_t21x_dtsi",
        "//vendor/nvidia/kernel:all_nvidia_dts",
    ],
)

dtb(
    name = "tegra210-jetson-tx1-p2597-2180-a01-android-devkit.dtb",
    srcs = ["tegra210-jetson-tx1-p2597-2180-a01-android-devkit.dts"],
    generate_symbols = True,
    deps = [
        ":all_t21x_dtsi",
        "//vendor/nvidia/kernel:all_nvidia_dts",
    ],
)

dtb(
    name = "tegra210-p3448-0000-p3449-0000-a02-android-devkit.dtb",
    srcs = ["tegra210-p3448-0000-p3449-0000-a02-android-devkit.dts"],
    generate_symbols = True,
    deps = [
        ":all_t21x_dtsi",
        "//vendor/nvidia/kernel:all_nvidia_dts",
    ],
)

dtb(
    name = "tegra210-p3448-0002-p3449-0000-a02-android-devkit.dtb",
    srcs = ["tegra210-p3448-0002-p3449-0000-a02-android-devkit.dts"],
    generate_symbols = True,
    deps = [
        ":all_t21x_dtsi",
        "//vendor/nvidia/kernel:all_nvidia_dts",
    ],
)

dtb(
    name = "tegra210-p3448-0000-p3449-0000-b00-android-devkit.dtb",
    srcs = ["tegra210-p3448-0000-p3449-0000-b00-android-devkit.dts"],
    generate_symbols = True,
    deps = [
        ":all_t21x_dtsi",
        "//vendor/nvidia/kernel:all_nvidia_dts",
    ],
)

dtb(
    name = "tegra210-p3448-0002-p3449-0000-b00-android-devkit.dtb",
    srcs = ["tegra210-p3448-0002-p3449-0000-b00-android-devkit.dts"],
    generate_symbols = True,
    deps = [
        ":all_t21x_dtsi",
        "//vendor/nvidia/kernel:all_nvidia_dts",
    ],
)

dtb(
    name = "tegra210-p3448-0003-p3542-0000-android-devkit.dtb",
    srcs = ["tegra210-p3448-0003-p3542-0000-android-devkit.dts"],
    generate_symbols = True,
    deps = [
        ":all_t21x_dtsi",
        "//vendor/nvidia/kernel:all_nvidia_dts",
    ],
)

dtb(
    name = "tegra210-loki-e-p2530-0030-e01-00.dtb",
    srcs = ["tegra210-loki-e-p2530-0030-e01-00.dts"],
    generate_symbols = True,
    deps = [
        ":all_t21x_dtsi",
        "//vendor/nvidia/kernel:all_nvidia_dts",
    ],
)

dtb(
    name = "tegra210-loki-e-p2530-0030-e02-00.dtb",
    srcs = ["tegra210-loki-e-p2530-0030-e02-00.dts"],
    generate_symbols = True,
    deps = [
        ":all_t21x_dtsi",
        "//vendor/nvidia/kernel:all_nvidia_dts",
    ],
)

dtb(
    name = "tegra210-loki-e-p2530-0030-e03-00.dtb",
    srcs = ["tegra210-loki-e-p2530-0030-e03-00.dts"],
    generate_symbols = True,
    deps = [
        ":all_t21x_dtsi",
        "//vendor/nvidia/kernel:all_nvidia_dts",
    ],
)

dtb(
    name = "tegra210-loki-e-p2530-0031-e01-00.dtb",
    srcs = ["tegra210-loki-e-p2530-0031-e01-00.dts"],
    generate_symbols = True,
    deps = [
        ":all_t21x_dtsi",
        "//vendor/nvidia/kernel:all_nvidia_dts",
    ],
)

dtb(
    name = "tegra210-loki-e-p2530-0031-e02-00.dtb",
    srcs = ["tegra210-loki-e-p2530-0031-e02-00.dts"],
    generate_symbols = True,
    deps = [
        ":all_t21x_dtsi",
        "//vendor/nvidia/kernel:all_nvidia_dts",
    ],
)

dtb(
    name = "tegra210-loki-e-p2530-0031-e03-00.dtb",
    srcs = ["tegra210-loki-e-p2530-0031-e03-00.dts"],
    generate_symbols = True,
    deps = [
        ":all_t21x_dtsi",
        "//vendor/nvidia/kernel:all_nvidia_dts",
    ],
)

filegroup(
    name = "dtbs",
    srcs = [
        "tegra210-baracus.dtb",
        "tegra210-jetson-tx1-p2597-2180-a01-android-devkit.dtb",
        "tegra210-p3448-0000-p3449-0000-a02-android-devkit.dtb",
        "tegra210-p3448-0002-p3449-0000-a02-android-devkit.dtb",
        "tegra210-p3448-0000-p3449-0000-b00-android-devkit.dtb",
        "tegra210-p3448-0002-p3449-0000-b00-android-devkit.dtb",
        "tegra210-p3448-0003-p3542-0000-android-devkit.dtb",

        "tegra210-loki-e-p2530-0030-e01-00.dtb",
        "tegra210-loki-e-p2530-0030-e02-00.dtb",
        "tegra210-loki-e-p2530-0030-e03-00.dtb",
        "tegra210-loki-e-p2530-0031-e01-00.dtb",
        "tegra210-loki-e-p2530-0031-e02-00.dtb",
        "tegra210-loki-e-p2530-0031-e03-00.dtb",
    ],
)
